# -*- coding: utf-8 -*-
"""
Script para processamento, limpeza, normalização e deduplicação
de todos os alunos das 43 turmas contidas no documento do Censo CEEP.
"""

import json
import re
import unicodedata

raw_turmas = {
    "Turma 1 (Pág. 1)": [
        "AGATHA SANTANA", "ALICE ALVES ANDRADE", "ANDRIO KAUAN SOUZA CRUZ", "ANTHONY LUIGE SILVA NOVAIS",
        "ANTHONY PIETRO DOS SANTOS", "ARIADNE ARAUJO DOS SANTOS", "ARIEL LUCAS DOS SANTOS", "CARLOS DANYEL VICENTE DOS SANTOS",
        "CELSO SOBRINHO MENDES", "CHAENE SILVA ROCHA", "DAVI SOUZA DE OLIVEIRA", "DAVY SANTOS FERNANDES",
        "DHEMILLY ALCANTARA SANTOS", "ERICK DA SILVA MACEDO", "GEOVANE SILVA TELES DOS SANTOS", "GUILHERME MENDES SOUZA",
        "IGOR SOUZA DA SILVA", "ISABELLA FERREIRA SANTOS", "ISADORA SAMILLY SANTANA TEIXEIRA", "JOAO GABRIEL SANTOS OLIVEIRA",
        "JOSE PAULO LIMAS DA SILVA", "KAROLLINE DOS ANJOS", "KETELYN ALESSANDRA SANTOS FERREIRA", "LEONARDO FERREIRA DOS SANTOS",
        "LIVIA SATELES FERREIRA PEREIRA", "LORRAN SA TELES PINTO", "LUCAS LORRAN ALVES MIRANDA", "LUCAS SILVA CHAVES",
        "MANOEL HENRIQUE ALMEIDA VIEIRA", "MICAEL ALVES DOS SANTOS", "PEDRO HENRIQUE CRUZ DOS SANTOS",
        "PEDRO HENRIQUE DOS ANJOS ALVES", "VITORIA SA TELES DE SOUZA", "THAILA DE SOUZA VIEIRA",
        "PAULO VICENTE VIEIRA DE OLIVEIRA CARMNA", "KEMMEL PEDRO COSTA DE SANTANA"
    ],
    "Turma 2 (Pág. 2)": [
        "ALEX SOUZA DE OLIVEIRA", "ALICIA BARBOZA OURIVES DE SOUZA", "ANA BEATRIZ MOREIRA PEREIRA",
        "BRENO FERNANDES PARDINI CORREIA", "CARLOS EDUARDO SILVA SANTOS", "CAROL CONCEICAO COSTA",
        "CRISLAINE DA SILVA PAZ", "DAVI ALVES NOVAES", "ENDRIO KAIAN VIEIRA DE ALENCAR", "ERCILIA MARIA SANTANA NERY",
        "ERIK SILVA SOUZA", "ESTEFANE DOS SANTOS COELHO", "FABIO WENDEL DOS SANTOS", "FERNANDA ANJOS DE JESUS",
        "GABRIEL ARAUJO SANTANA", "GEOVANA RIBEIRO LOPES", "GUSTAVO SILVA PEREIRA", "ISABELA CRISTINA MESSIAS PAZ",
        "ISABELA DE SOUZA SANTOS", "ISMAEL OLIVEIRA DO CARMO", "JOAO PEDRO SANTOS AQUINO", "JOAO VITOR CHAVES DOS SANTOS",
        "KAIO RICARDO BRITO CAVAUCANTE", "KAIRO LUCAS SILVA SA TELES", "KAROL VIEIRA DO NASCIMENTO", "KAUANNE ARAUJO SOUSA",
        "KYARA RUANA OLIVEIRA PIRES", "LARA GABRIELLE QUEIROZ E ARAUJO", "LARA NADIR MASCARENHAS FRANCA",
        "LIPE CORREIA BITTENCOURT CARIBE", "MARIA EDUARDA SILVA DE SOUZA", "MARIA VITORIA DA SILVA SOUZA",
        "MIGUEL VIEIRA RIBEIRO", "PIETRO MEDEIROS NERI", "RAONY GONCALVES SANTOS", "RUAN CARLOS SOUZA ALVES",
        "SAMUEL MARTINS DE SOUZA", "TAUANY KEVILLY SOUZA DOS SANTOS", "UEMERSON SILVA SAMPAIO"
    ],
    "Turma 3 (Pág. 3)": [
        "ADRIANO CEDRO CHAVES", "AGATHA EVELYN VIEIRA SILVA", "BRAYAN SOUZA DE OLIVEIRA", "BRENDA FERNANDES DE OLIVEIRA",
        "CARLOS HENRIQUE SILVA SANTOS", "CRISTIANO RONALDO DOS SANTOS NOVAES", "DIEGO DOS ANJOS SANTOS",
        "EDSON APOLINARIO DE SA FILHO", "ERISON DE SOUZA CARNEIRO", "EVA OLIVEIRA SILVA", "FERNANDA KEURI QUEIROZ DE SOUZA",
        "FLAVIA VITORIA VICENTE ARAUJO", "FREDERICO ARAUJO NOVAIS", "GABRIEL JOSE OLIVEIRA DE SOUZA", "GABRIEL SOUZA SILVA",
        "HENRY GABRIEL SOUZA SILVA", "HENZO MENDES PEREIRA", "HIAGO ANJOS OLIVEIRA", "JEFERSON OLIVEIRA DE SOUZA",
        "JOAO VITOR DO CARMO MARTINS DE NOVAIS", "LUCIANE PEREIRA DOS SANTOS", "LUDMILA BISPO ARAUJO",
        "LUIS FERNANDO SA TELES DE OLIVEIRA", "LUIS HENRIQUE CASTRO AQUINO", "LUNA VITORIA OLIVEIRA PEREIRA",
        "MARCOS ANTONIO OLIVEIRA DE SOUZA", "MARIANE DOS SANTOS ANJOS", "MIGUEL FELIPE MOITINHO BARRETO",
        "PAULO CESAR NERES VIEIRA", "PEDRO DAVI PIRES DOS ANJOS", "PEDRO GABRIEL SANTOS VIEIRA", "PEDRO RAFAEL SOUZA SANTOS",
        "RAFAEL CAMARA ASSUNCAO", "ROBSON SANTOS SOUZA", "VINICIUS AQUINO", "VITOR OLIVEIRA DE SOUSA",
        "VITOR ROCHA DOS SANTOS", "WENDEL ALVES DOS SANTOS"
    ],
    "Turma 4 (Pág. 4-5)": [
        "ADELIA VITORIA DAMACENO", "ALICIA NOVAIS BRAGA", "ALINE SANTOS RIBEIRO", "ANA LIS OLIVEIRA SOARES",
        "BEATRIZ FERREIRA SANTOS", "BERNARDO DOS SANTOS NETO", "CARLOS ALEXANDRE DE ARAUJO CUNHA", "EMANUELY OLIVEIRA DOS SANTOS",
        "EVELYN ALCANTARA DA SILVA", "GABRIEL SOUZA TELES BASTOS", "GABRIELA ARAUJO DE SOUZA", "GIOVANNA CARNEIRO VELOSO",
        "GUSTAVO TEIXEIRA SOUZA", "GUSTAVO YAN OLIVEIRA NOVAIS", "HEITOR JOAO SOUSA BRANDAO", "HELOISA TEIXEIRA TELES",
        "HENZO MANOEL TEIXEIRA MENDES", "JAMILE NASCIMENTO DA SILVA", "LARA LAYS SA TELES TEIXEIRA VAZ",
        "LARYSSA GABRIELA SILVA DOS SANTOS", "LAURA KATARINE FARIAS SILVA", "LAURA VALADARES DE ARAUJO",
        "LUANA CAVALCANTE BATISTA", "LUIS OTAVIO TELES RIBEIRO", "LUIZ FELIPE SANTOS FERREIRA",
        "MARCO ANTONIO MOURA PIRES LIMA", "MARIA CLARA ANJOS TELES", "MARIA ISABELA SANTOS NEVES",
        "MERYLLYN ANGELICA DE BRITO LIMA", "MICHELLE GONCALVES DE SOUZA", "MONALISA FARIAS DA SILVA",
        "PALOMA SOFIA SANTOS", "PEDRO LOHRAN MIRANDA PEREIRA", "PIETRO JOSE TEIXEIRA DE SOUZA",
        "RAISSA WALENTINA DE SOUZA TELES", "RAYSSA OLIVEIRA SILVA", "SABRINA MACEDO DE SOUZA",
        "SOFIA SOUZA VIEIRA", "THAYSLA VICTORIA SOUZA SILVA", "VITORIA KETLEN OLIVEIRA DE SOUZA", "WILTON SOUZA OLIVEIRA JUNIOR"
    ],
    "Turma 5 (Pág. 6-7)": [
        "ADEILZA SILVA FERNANDES", "ADRIANY SA TELES RIBEIRO", "ADRIELLY JESUS DA SILVA", "ALICE ARAUJO RAMOS",
        "AYNNA LOUISE PURIFICACAO SOUZA", "BRENDA DOS SANTOS ARAUJO", "BRUNA SANTOS CUNHA", "COSME WENDEL SILVA RIBEIRO",
        "DANYEL SILVA ARAUJO", "EDSON RIBEIRO DOS ANJOS", "ELEN AIANE ALCANTARA DOS SANTOS", "ELOANE MARQUES DOS PASSOS",
        "ELIADINA NEPOMUCENO MARTINS", "GEOVANA MOITINHO MARTINS", "GUILHERME DE JESUS RIBEIRO",
        "HENRY AUGUSTO OLIVEIRA DE SOUZA BRITO", "ICARO FELIPE DE OLIVEIRA", "INGRID DRIELY GUIMARAES DE SOUZA",
        "ISABELLA AMARAL DE OLIVEIRA", "IZA NICOLLY DE LIMA FRAGA", "JOAO HENRIQUE PASSOS DE SOUZA",
        "JOAO LUCAS NOVAIS PEREIRA", "JULIA SANTOS OLIVEIRA", "KAMILLY VITORIA SOUZA SANTOS", "KAROLLAINE NOVAIS FERNANDES",
        "KAUA SOUZA NUNES", "KEMILLY VITORIA XAVIER SOUZA", "LUAN RANGEL LOPES DA SILVA", "LUCIO ALEJHANDRO MENDES DA SILVA",
        "LUIS FERNANDO SILVA SANTOS", "LUIZ FERNANDO SILVA BARROS", "LUIZ HENRIQUE OLIVEIRA SOUSA REIS",
        "LUNA ALVES DE OLIVEIRA", "MAHYRA KAROL SANTOS NASCIMENTO", "MATHEUS PHILLIPE SOUZA SANTOS",
        "MICHEL FERREIRA DE JESUS", "MOISES FIGUEREDO SAMPAIO NETO", "NICOLE ALVES RAMOS", "PEDRO HENRIQUE NOGUEIRA SOUZA",
        "PEDRO HENRIQUE RODRIGUES DOS ANJOS", "MIRELE MARQUES PASSOS", "RODRIGO SANTOS DE OLIVEIRA", "WILLIAN CARDOSO DOS SANTOS"
    ],
    "Turma 6 (Pág. 8-9) - Turma dos Entrevistadores (1º ADM CM)": [
        "ANA JULIA TEIXEIRA", "ANA LUIZA SOUZA CERQUEIRA", "BRUNO MARTINS MENDES", "EVERTON SILVA MARTINS",
        "GEOVANA SANTOS", "GUILHERMY SANTOS LIMA", "HAVILA ELOAH SANTOS BARBOSA", "HENDRIK SANTOS DE ARAUJO",
        "IGOR GABRIEL SILVA DE SOUZA", "ISADORA SANTOS RODRIGUES", "IZABELA TEIXEIRA PINTO", "JARBAS LEONARDO SANTOS MEDEIROS",
        "JEFERSON PEREIRA DE SOUZA", "JOAO PEDRO ALCANTARA DOS ANJOS", "JOAO VITOR ROCHA BASTOS", "JULIA SOPHIA JESUS DA SILVA",
        "KLEBER SILVA DE ANDRADE", "LAIS HELENA ANJOS OLIVEIRA", "LINE LORRANE LUIS DE SOUZA", "LUCAS SOUZA ALCANTARA",
        "MARIA BEATRIZ TEIXEIRA SANTOS", "MARIA EDUARDA SANTOS SOUZA", "MARIA EDUARDA SOUZA BASTOS", "MARLON SILVA SOUZA",
        "MATHEUS SILVA DA COSTA", "MICHAEL SANTOS LIMA", "MIGUEL DA SILVA LIRA NUNES", "MIRIAN ANJOS VIEIRA",
        "NATALY BRENDA BARBOSA SILVA", "NICOLAS RIAN DOS SANTOS", "PEDRO HENRIQUE BARBOSA SILVA", "RAONY GABRIEL DIAS VAZ",
        "SAMANTA EVELIN BERNARDES ARAUJO", "SAMYRA DA FONSECA TEIXEIRA", "STEFANY ALVES ROCHA", "TAYANE DA SILVA SANTOS",
        "TAYLON WILLIAN OLIVEIRA SANTANA", "THAYLA SENA ROLDAO DOS SANTOS", "YANNE KESSIA DE SOUZA ALMEIDA",
        "FLÁVIA ALESSANDRA LIMA SANTOS", "ANANDA CATHALÁ GUIMARÃES Á. FERREIRA"
    ],
    "Turma 7 (Pág. 10)": [
        "ANA JULIA SOUZA OLIVEIRA", "ANNA VITORIA BRANDAO DA SILVA", "ARIANE NOVAIS DOS ANJOS", "ARLEN GUSTAVO SILVA SOUZA",
        "BRENO OLIVEIRA SILVA", "DANIEL ARAUJO ALMEIDA", "DIEGO ARMANDO DOS SANTOS NOVAES", "DIOGO RAMOS LUCENA",
        "ELAINE SANTOS MENDES", "EVERTON SOUZA SANT ANA", "GABRIEL DOS ANJOS BRANDAO", "INACIO CAUA BRANDAO ARAUJO",
        "JEFERSON RUAN SILVA ANJOS", "JOAN SOUZA OLIVEIRA", "JODSON DOS ANJOS NOVAES", "KATILLY VITORIA CRUZ DE SOUSA",
        "KEILANE ARAUJO SOUZA", "LIVIA SANTOS DE JESUS", "MANUELA SANTOS MENDES", "MARCOS TARCISIO DE SOUZA MIRANDA",
        "MARIA CECILIA SANTOS DE SOUZA", "MARIA CLARA BASTOS DOS ANJOS", "MARIA PAULA PINTO",
        "MARIANE BEATRIZ BRANDAO DA SILVA", "MARLAN RODRIGUES CAVALCANTE", "NATHALY VITORIA SOARES DE ALMEIDA",
        "NICOLE REBOUCAS ALVES", "PEDRO HENRIQUE DOS REIS SILVA", "PIETRO VIEIRA FAGUNDES", "ROSELAINE LIMA DOS SANTOS",
        "SUSANE MENDES DE SOUZA", "UEVERTON SANTOS DE CASTRO", "WANDERSON SANTOS ARAUJO", "NATALY MICAELY DE OLIVEIRA",
        "ALISSON DOS SANTOS", "MARCELO VIANA", "ANNE CAROLINE PAIVA", "RUAN ALVES OLIVEIRA"
    ],
    "Turma 8 (Pág. 12-13)": [
        "AILTON REIS ALVES JUNIOR", "AKILI DE JESUS SANTA RITA", "ALEXANDRINO JOSE OLIVEIRA FERREIRA", "ANA ELISA SOUZA",
        "ANTONIA OLIVEIRA SANTOS", "CASSIO BARBOSA DE OLIVEIRA", "DANIEL DA SILVA SANTOS", "DHENNIFER BARBOSA DO NASCIMENTO",
        "EDIRLEI CARLOS ANJOS DOS SANTOS", "EDNILTON MENDES", "EDUARDO OLIVEIRA DE SOUZA", "EMANUEL DOS SANTOS",
        "EMILLY LUANE FERNANDES DE MELO", "ERICK SANTOS DE SOUZA", "GABRIEL AURELIO DE OLIVEIRA",
        "GILVAN DE OLIVEIRA SANTOS JUNIIOR", "GLEIDSON LIMA MENDES", "GUILHERME SOUZA LOPES", "HENDRICK CAUE MENDES RODRIGUES",
        "HENRY MENDES DE OLIVEIRA", "IBSON SILVA RODRIGUES", "ISABELLI EICHILA SILVA ALENCAR", "JANICE SOUZA DOURADO",
        "JOAO HENRIQUE CONCEICAO DOS ANJOS", "KAELLE DA SILVA SANTOS", "KAILAN DOS SANTOS TEIXEIRA",
        "LAIANE CONCEICAO DOS SANTOS", "LINDERSON MENDES RODRIGUES", "LIZ CAMILLY DE ANDRADE MENDES", "MARIA LUIZA SOUZA",
        "MARIANE GABRIELE PINA DE OLIVEIRA", "MARLA ARIANY NOVAES DA SILVA", "PABLO LORRAN DOS ANJOS BARROS",
        "RAY ALVES SANTANA", "RODRIGO CESAR MENDES ALCANTARA", "TARCIO SOUZA MENDES", "TARCISO SOUZA RIBEIRO",
        "THYERRY LEVI BRANDAO LOPES", "VITOR MANOEL MENDES SANTOS", "WESLEY LORRAN MENDES RODRIGUES", "ISABELA CRISTINA SOUZA SANTOS"
    ],
    "Turma 9 (Pág. 14)": [
        "ANA ISABELA FERREIRA DE SOUZA", "ANDRESSA OLIVEIRA SOUZA", "ARIANA SILVA SOUZA", "BRUNA SOUZA DE ARAUJO",
        "DAVY LIMA SANTOS", "ELISA MAIARA BRANDAO DE NOVAES", "EMERSON DOS SANTOS ROCHA", "ENDRIK CASSIO DOS SANTOS ANJOS",
        "ENDRIK RAMON SANTOS OLIVEIRA", "ERIK RIAN SANTOS BRANDAO", "ERYK DOS ANJOS VASCONCELOS", "EVELIN SANTOS MACEDO",
        "FELICIA BRAGA DE SOUZA", "FLAVIO JOSE OLIVEIRA SANTOS", "GABRIEL BRAGA SILVA", "GUSTAVO SOUZA MENDES",
        "ISABEL FERREIRA VAZ", "ISAEL LOURENCO PINTO NETO", "ITHALLO BERNARDO SANTOS SOUZA", "JACKSON EDUARDO BRANDAO SANTOS",
        "JENNIFER EMANUELE RAMOS DOS SANTOS", "JENYFER SANTOS DE OLIVEIRA", "KAWANNY SOUZA SANTOS",
        "KELVIN BRAIAN FRANCISCO DA SILVA", "LUANA LIMA DE SOUZA", "MARCOS PAULO SOUZA", "MARIA EDUARDA SANTOS SOUZA",
        "PAULO VICTOR BARBOSA DE ARAUJO", "PEDRO VINICIUS DE SOUZA BARBOSA", "SAMUEL SILVA PINTO",
        "SANTIAGO GONCALVES DE NOVAIS", "THAISLANE SANTOS DE SOUZA", "VITOR KAUE SOUZA GOMES", "VITOR RIAN ALMEIDA BRANDAO",
        "WESLLEY SILVA FERNANDES", "SAMMY RODRIGUES DOS ANJOS", "CARLOS EDUARDO SANTOS", "HENZO MENDES PEREIRA"
    ],
    "Turma 10 (Pág. 16)": [
        "ADSON BATISTA DE SOUZA", "ALICE VIEIRA", "ANA FLAVIA SANTOS DE OLIVEIRA", "ANDERSON JOHAN CARMO DE JESUS",
        "ANDRESSA OLIVEIRA GONCALVES", "ANNE APARECIDA DOS ANJOS DOURADO", "ANTONY DA FONSECA NOVAIS", "BEATRIZ OLIVEIRA SANTOS",
        "BIANCA SANTOS DE OLIVEIRA", "CRISTIANO RONALDO ANJOS DE SOUZA", "ERIC DE ASSUNCAO RAMOS", "ERIK OLIVEIRA DE SOUZA",
        "GABRIEL SANTOS DE ALMEIDA", "HUGO RAFAEL MARQUES SILVA", "JAINE DOS ANJOS NUNES", "JULIA ALVES", "LAURA SILVA TEOTONIO",
        "LETICIA ALVES DE SOUZA", "LUCAS ALCANTARA ALVES", "NATALY VITORIA SILVA DOS SANTOS", "PAOLA OLIVEIRA ALVES",
        "PEDRO HENRIQUE SIZENANDO BARBOSA", "PEDRO HENRIQUE VIEIRA PAIVA", "RAFAELA MENDES DOS SANTOS",
        "RENNERSON NUNES DE OLIVEIRA", "SABRINA ALVES DE SOUZA", "STEFANYE REIS DO SANTOS", "TALYTA ALVES DE SOUZA",
        "THALINE DA SILVA ALVES", "YASMIN DE SOUZA TELES", "GABRIEL SANTOS DAMACENA"
    ],
    "Turma 11 (Pág. 18-19)": [
        "AIALA MENDES SOUZA", "CAROL OLIVEIRA ARAUJO", "ENZO MATHEUS ALVES DAMASCENA", "ESTER BRANDAO SILVA",
        "GEOVANNA BRITO DE OLIVEIRA", "GEOVANNA CAMPOS DA HORA", "GUTIERRE NOVAES MATOS", "HENZO THIAGO MENDES GONCALVES",
        "HILMA NARA SANTOS SILVA", "IARLEY ANTUNES SOUZA", "INGRIDY LORRANY SOUZA RIBEIRO", "ISABELA OLIVEIRA SOUZA",
        "ISLA SA TELES DO NASCIMENTO", "JAMILE SILVA PINTO", "KARLA NATALIA SOUZA SANTOS", "KEVELYN VITORIA SOUZA ARAUJO",
        "LORENA SOUZA DOS ANJOS", "LORRANNY EDUARDA MOREIRA MENDES", "LUANA SILVA MENDES", "LUCIANA LIMA BRANDAO",
        "MARISSOL TEIXEIRA DINIZ", "MARJORIE ELOA DE SOUZA SANTOS", "MATHEUS MACEDO DE LUNA SANTOS", "MURILO SOUZA OLIVEIRA",
        "NATHALY MICAELY DE OLIVEIRA", "NEILA MENDES NASCIMENTO", "PAMELLA ALCANTARA MARQUES", "PEDRO FELIPE SOUZA COSTA",
        "PIETRA SOFIA DOS SANTOS SOUZA", "RAFAELLA BRANDAO SOUZA", "RAYLLON BARROS LOPES", "RUAN OLIVEIRA DE SOUZA",
        "TAILANE SOUZA SANTOS", "THAINAN ANJOS DE OLIVEIRA", "THAVLLY NAUANA CONCEICAO DA SILVA", "VITORIA RODRIGUES FARIAS",
        "VITORIA VIANA ALVES", "REVELYN VITORIA SOUZA", "KEVILEN VITORIA ARAUJO DOS SANTOS"
    ],
    "Turma 12 (Pág. 20-21)": [
        "ANA ELLEN NOVAIS DE SOUZA", "ANNA GIULIA SANTOS LISBOA", "ARIELLY SOUZA NOVAIS", "BEATRIZ DE SOUZA SANTOS",
        "BRENDA RODRIGUES JESUS DA SILVA", "CAMILA RIBEIRO ARAUJO", "CLARA IASMIN DE SOUZA", "DANIEL ALVES ARAUJO",
        "DAVI SILVA DE OLIVEIRA", "DHEBORA SILVA VASCONCELOS", "EMILIA SOUZA LOPES", "EMILLE ANNE XAVIER DE SOUZA",
        "ERICA SANTOS NEVES", "EVELYN QUEIROZ COSTA", "GABRIEL CAVALCANTE DA SILVA", "GEOVANNA VIEIRA NERIS",
        "ISABELA CRISTINA SOUZA DOS SANTOS", "ISABELA SANTANA DE SOUZA", "ISLANY MENDES GOMES DE OLIVEIRA",
        "JADDY PALLOMA VIEIRA SOUZA", "JARBAS LEONARDO SANTOS MEDEIROS SOBRINHO", "JARDIEL NASCIMENTO MENEZES",
        "LARA CRISTINY SOUZA SANTOS", "LARA LAIS DE SOUZA", "LUDMILLA SOARES DE ARAUJO", "LUIS OTAVIO SOUZA SANTOS",
        "MARCO ANTONIO VIEIRA ALVES", "MARIA JULLIA OLIVEIRA DA SILVA", "MARIA LUIZA OLIVEIRA BORGES",
        "NATALY SANTANA ALVES", "NATIELLY SOUZA ARAUJO", "NATYELE SILVA RODRIGUES", "PALOMA NATHALY MENDES DE JESUS",
        "RAVI DE ALMEIDA SANTOS", "RUAN MENDES DE SOUZA", "TALISSON DE NOVAIS MOTA", "WENDERSON SANTOS PIRES",
        "VINICIUS CORREIA BATISTA"
    ],
    "Turma 13 (Pág. 22)": [
        "ALANA NICOLY DE ARAUJO SA TELES", "ALYSSON JUAN SOUZA OLIVEIRA", "ANA BEATRIZ MACHADO DOS ANJOS",
        "ANA LUISA DOS SANTOS OLIVEIRA", "DAFINY REBOUCAS GOMES", "DANIEL SANTANA DOS SANTOS", "EMILLY BRANDAO DOS SANTOS",
        "ERIC OLIVEIRA GUIMARAES", "EVELYN DE ALCANTARA FERREIRA", "FELIPE ALVES MATOS", "HIARLEY TELES OLIVEIRA",
        "JEOVANA BISPO ARAUJO", "JHONATA OLIVEIRA DOS ANJOS", "JOAO PEDRO DA SILVA ALVES", "JULIA MENDES DOS SANTOS",
        "KEVILEN VITORIA ARAUJO DOS SANTOS", "LARA SOFIA NOVAES SOUZA", "LARISSA SOUZA CONCEICAO", "LUCIANY RIBEIRO BARROS",
        "MAICOM FERNANDO DE OLIVEIRA SILVA", "MARIA KETHELLYN RIBEIRO DE SOUZA", "MARIA LUISA FERREIRA VIEIRA",
        "MARIA LUIZA SANTOS SOUZA", "NAIANE DE SOUZA", "PEDRO IURE SOUZA NOVAIS", "RAFAELA SOUZA NEVES",
        "SAMMY RODRIGUES DOS ANJOS", "THALYSON LYAN LIMA DA SILVA", "VICTOR EDUARDO SANTOS OLIVEIRA", "WALLEX MENDES DE SOUZA",
        "WELINGTON PAULO SANTOS BARRETO", "WESLEI ALVES PEREIRA", "YASMIM SOUZA SILVA", "GABRIEL SILVA SOUZA",
        "JULIA SANTOS OLIVEIRA", "MONALISA FARIAS DA SILVA"
    ],
    "Turma 14 (Pág. 24-25)": [
        "ALANNA JULIA ALVES DE SOUZA", "ANA CRISTINA SILVA SANTOS", "ANA JULIA RAMOS NEVES", "ANA PAULA PORTO AZEVEDO",
        "ANNA CLARA TEIXEIRA DE ARAUJO", "ANNE CAROLINE TELES PAIVA", "ARTUR GUILHERME DA SILVA RIBEIRO",
        "CARLOS MATHEUS DE SOUZA AQUINO", "DAFYNE SILVA SOUZA", "ELOA CRISTINA BARROS DOS ANJOS", "ELOA DE SOUZA",
        "EMILIA MOREIRA AQUINO", "EMILLY SOPHIA SANTOS MACEDO", "ERICK MENDES BRAGA", "EVILLYN SANTOS DO NASCIMENTO",
        "EWERTON HIAN MATOS TELES", "GUILHERME DE SOUZA ALMEIDA", "HELOYSA NATIELLY SANTOS DE OLIVEIRA",
        "HENRY BRANDAO DE SOUZA", "IALI SAMPAIO GAMA", "ILZA NAELY MENDES LIMA", "INGRID THAUANE MATOS TELES",
        "ISABELA SANTOS PEREIRA", "ISABELLA RODRIGUES BISPO", "ISABELLA SANTOS SOARES", "ISAURA FIGUEREDO DE ATHAYDE",
        "JAMYLLE MACIEL OLIVEIRA", "JOEL MARIO SOUZA SANTOS", "JULYA SA TELES BARBOSA", "KEVELY NICOLE SANTOS SOUZA",
        "LARA KATARINE OLIVEIRA RABELO", "MARIA CLARA BARROS FRANCA DE LIMA", "MARIA ISLA SANTOS DE SOUZA",
        "NATHYELE SILVA CAETANO", "PEDRO HENRIQUE SANTOS SILVA", "PEDRO VIEIRA BRANDAO BRAGA", "PIETRO DOS SANTOS PIRES",
        "SAULO MACHADO", "KEMILLY BEATRIZ COSTA SÁ TELES PIRES", "UALISON DA SILVA MACHADO"
    ],
    "Turma 15 (Pág. 26)": [
        "ALANA AMORIM DE SOUZA", "ANA CAROLINA SANTOS ARAUJO", "ANTHONY GABRIEL SOUZA DOS SANTOS",
        "CARLOS GABRIEL GONCALVES DE SOUZA", "CASSIA RAYANNY SANTOS OLIVEIRA", "CLARA MENDES MARTINS",
        "DANIEL DA SILVA CHAGAS", "ELAINE SANTOS MENDES", "ELOA SOUZA NOVAES", "EMILE VITORIA DE JESUS SILVA",
        "EMILY VITORIA FERREIRA VASCONCELOS", "ESMERALDA SOLEDADE SILVA TEIXEIRA", "EVERTON RICARDO SOUZA ALVES",
        "GABRIELI NERIS DA SILVA", "GUILHERME DOS ANJOS SANTOS", "IZABEL NOVAES DA SILVA", "JEAN PEREIRA RIBEIRO",
        "JOAO VITOR SANTOS DE SOUZA", "KAUAN ARAUJO SILVA", "LEONARDO OLIVEIRA DOS SANTOS", "LUANA OLIVEIRA DE ARAUJO",
        "LUCAS WENDELL ALCANTARA PEREIRA", "LUIS FELLIPE FERREIRA LOPES", "MARIA FERNANDA FERNANDES MENDES",
        "MICAELE SANTOS DA SILVA", "MICHELE REBECA MENDES", "MILENA IZABELE DA CONCEICAO SANTOS", "MILENA SANTOS MENDES",
        "PEDRO ARTUR SANTOS NOVAES", "PRISCILA LOARA RODRIGUES MENDES", "RAFAEL SANTOS BARROS", "TAINA LORRANE ALVES DOS SANTOS",
        "WENDELL LUIZ JESUS DE SOUZA", "YURI VIEIRA BAHU", "MICAELE SANTOS MENDES", "ALANA NICOLY DE ARAUJO SÁ TELES"
    ],
    "Turma 16 (Pág. 44-45)": [
        "ADAELTON DE SOUZA JUNIOR", "ALVARO HENRIQUE VIEIRA DE SOUZA", "AUGUSTO BISPO RIBEIRO",
        "CARLOS EDUARDO FERREIRA DE ALMEIDA SANTOS", "DEIVISON ALMEIDA CHAVIEL", "EDUARDO OLIVEIRA DE ARAUJO",
        "ELAINE CAVALCANTE DOS SANTOS", "FELIPE PIRES ANJOS", "GABRIELA FRANCA DIAS", "GUILHERME FERREIRA LOPES",
        "HENZO GONDIM MACHADO", "IAN RODRIGUES TEIXEIRA", "ISABELE DREGER SANTOS", "ISLA LORRAINE SANTOS DOS ANJOS",
        "JAMYLLE DE SOUZA PEREIRA", "JULIA ROSA DE PAULA MOREIRA", "KATIELLY SOUZA OLIVEIRA", "KAUA SOUZA AZEVEDO",
        "KELVE MOURA SERAFIM", "KEVEN KAILAN FERNANDES GONCALVES", "LAURA LIS ALCANTARA ANJOS", "LUIS GUSTAVO ALVES DOS ANJOS",
        "LUMA GONCALVES DE ALMEIDA", "MARCOS PAULO MENDES GUIMARAES", "MARCOS VITOR SILVA TEIXEIRA",
        "MARIA EDUARDA SANTOS RAMOS", "MICAELE DE SOUZA NOVAIS", "MIGUEL VIEIRA MATOS", "MILLENY SILVA SOUZA",
        "NATTAN MADUREIRA NUNES", "PEDRO LUCAS NUNES BASTOS", "PIETTRO SANTOS DE SOUZA", "RAI CLERISTON PEREIRA DOS SANTOS",
        "RAILAN GUSMAO DE MELO", "RAQUEL ALCANTARA OLIVEIRA", "RODRIGO OLIVEIRA FRANCO", "SAMUEL ROCHA SILVA",
        "SAVIO CAVALCANTE SOUZA", "TAIS SA TELES DOS SANTOS", "JOÃO PEDRO COSTA ALMEIDA"
    ],
    "Turma 17 (Pág. 46-47)": [
        "ALEX PEREIRA DE SOUZA", "ALEX THAUAN ALVES FRANCA", "ANDERSON FERREIRA DA SILVA", "ANDRE LUIS NOVAIS BRITO",
        "CARLOS EDUARDO JESUS DA SILVA", "CHRISTIAN ALVES SANTANA DA SILVA", "EDINILTON ALVES DE SA", "ELIZA VITORIA DE MELO PIRES",
        "HENZO COSTA SOUZA", "HUGO ALVES DA SILVA", "IARA LORRANE DE SOUZA PURIFICACAO", "ISABELLA GOMES ARAUJO",
        "JOAO PEDRO DE OLIVEIRA BATISTA", "JOAO VITOR SOUZA SANTOS", "JOSE VICTOR RAMOS OLIVEIRA", "KAUE DONATO DIAS",
        "KAUE GUILHERME DOS ANJOS SOUZA", "KEVIN VINICIUS PINA LEITE", "LAILSON DA SILVA CASSIMIRO",
        "LARA VICTORIA OLIVEIRA RIBEIRO", "LAZARO ANTONIO MAIA OLIVEIRA", "MARCOS PIETRO FELIX CIRILO",
        "MARIA JULLIA DE SOUZA FALCAO", "MATEUS MUNDURUCA DOS ANJOS", "MICHELY VICTORIA RODRIGUES DA COSTA",
        "MIGUEL DA SILVA BRITO", "NICOLLAS DOS ANJOS MATOS", "PALOMA MARTINS LOPES", "PAULO RANGEL ALVES DA SILVA",
        "PEDRO HENRIQUE DA SILVA AMORIM", "PEDRO INACIO LEAO SOUZA", "RAFAEL DE SOUZA BRANDAO", "RUAN ARAUJO DE SOUZA",
        "RYAN GABRIEL MENDES ANDRADE", "SERGIO MURILO BRITO BARBOSA", "TALITA SILVA NASCIMENTO",
        "THAUAN UALLAS BASTOS DOS SANTOS", "THIAGO FERREIRA NUNES", "UANDERSON JHONATAN SANTANA DE OLIVEIRA",
        "VITÓRIA DOLORES OLIVEIRA CARVALHO", "WENDER COSTA RODRIGUES", "YASMIN DOS SANTOS NASCIMENTO", "ALISSON VIEIRA MARTINS"
    ],
    "Turma 18 (Pág. 48)": [
        "ALANA NOVAES MOTA RIBEIRO", "ANA BEATRIZ OLIVEIRA DA SILVA", "ANA CLARA SILVA ROCHA", "ANA VITORIA CONCEICAO MENDES",
        "ANNA CLARA MENDES DE OLIVEIRA", "CAIO BARBOSA BRAGA DE SOUZA", "CAIO PEREIRA DOS SANTOS",
        "CARLOS HENRIQUE OLIVEIRA NUNES", "EDICARLOS SANTOS DA SILVA", "FELIPE SANTOS MARTINS", "GABRIEL CARVALHO SOUZA",
        "GILZA SILVA DE SOUZA", "IANDRA TAYSLA MONTEIRO ARAUJO", "JOAO HENRICK RAMOS OLIVEIRA", "JOAO VICTOR RIBEIRO DE SOUZA",
        "KELVIN DA SILVA SANTOS", "KELVIN NOVAES MENDES", "LAYS ARAUJO GABRIEL", "LAYSLA ANJOS OLIVEIRA",
        "LINCON VIEIRA OLIVEIRA", "LUNNA RAILLA BARBOSA SOARES", "LYS VICTORIA SANTOS DE OLIVEIRA", "MAENA OLIVEIRA PONTES",
        "MANUELA ALEXANDRA PINTO TEIXEIRA", "MATHEUS DE SOUZA SANTOS", "MIRELE SANTOS DOS ANJOS", "MIZAEL SILVA VIEIRA",
        "NATIELE SOUZA DOS SANTOS", "NICOLY LUNNA VIEIRA DE SOUZA", "PAULO VITOR BRAGA RIBEIRO", "STEFANY OLIVEIRA SILVA",
        "WENDER COSTA RODRIGUES", "YURI MATEUS BARROS ALVES", "JACIELE XAVIER DE ALMEIDA", "THIAGO ALCANTARA VIEIRA"
    ],
    "Turma 19 (Pág. 49)": [
        "AMANDA ALCANTARA DE OLIVEIRA", "ANA LUISA DELFINO REGIS", "ARIADINNE THALLIA SANTOS SILVA",
        "ARQUIMILSON OLIVEIRA SOUZA JUNIOR", "EMANOEL PIEDADE", "EMELLY FERREIRA DE SOUZA", "ERIC JOSE LIMA MORAIS",
        "FLAVIA OLIVEIRA DA SILVA", "GABRIEL GOMES ALMEIDA", "GABRIEL SOUZA FERNANDES", "GUSTAVO DE OLIVEIRA MATOS",
        "JULIA MIRANDA NOVAIS", "INACIO SILVA OLIVEIRA", "INGRID DA CRUZ SOUSA", "ISLA TAWANE ALCANTARA DE OLIVEIRA",
        "JOAO PEDRO SANTOS NEVES", "JONIVAN SOUZA LIMA JUNIOR", "JORGE ALAN SOUZA ARAUJO SANTOS", "KAIKE FABIO NEVES DE SOUZA",
        "LETICIA SANTOS DE JESUS", "LUIS FELIPE BENICIO DOS SANTOS", "MANUEL SILVA MELO FILHO", "MARIA CLARA DA SILVA NERIS",
        "MARIA CLARA DE OLIVEIRA", "MARIA EDUARDA DE SOUZA GRIGORIO", "PEDRO HENRIQUE SANTOS MACHADO", "RAFAEL ANJOS OLIVEIRA",
        "SAMIRA SOUZA PAIVA", "WEZIA SOUZA DE ALMEIDA", "THAUAN LIMA DOS SANTOS", "RIAN FELIPE SOUZA COUTINHO",
        "MIGUEL VIEIRA MATOS", "LUCAS RODRIGUES"
    ],
    "Turma 20 (Pág. 50)": [
        "ALISSON FEITOSA FARIAS", "ANA CLAUDIA DE SOUZA ARAUJO", "ANA VITORIA ROCHA TELES", "DAVYD RAMOS DE SOUZA",
        "ELOA BARRETO FRAGA", "ELOA SANTOS PIRES", "EMILLY VITORIA SANTANA RANGEL DOS SANTOS", "FABRICIA SOFIA BRANDAO SANTOS",
        "FRANCINY ANJOS VIEIRA", "GABRIEL SEBASTIAN SILVA NOVAES", "GABRIELA TELES CIDREIRA", "JHULLE BRANDAO TEIXEIRA",
        "JOAO MATEUS LIMA PIRES", "KAROLAYNE VITORIA SOUZA NOVAES", "KATHARINE LIMA FREITAS", "KEMILY VITORIA SILVA SOUZA",
        "LAISANNY TAUANY SOUZA SILVA", "LARA VITORIA OLIVEIRA MENDES", "LINDSY ALVES DOS SANTOS", "MARIA EDUARDA BASTOS SOUZA",
        "MARINA SIMONE SANTOS NUNES", "MATHEUS ARAUJO OLIVEIRA", "MATHEUS SOUSA DOS SANTOS", "PAMELA DA SILVA MACEDO",
        "PEDRO HENRIQUE OLIVEIRA DE SOUZA", "PEDRO HENRIQUE SOUZA MARTINS", "PEDRO LUCAS MENDES SANTANA",
        "PEDRO LUKA SOUZA REIS ARAUJO", "RAFAELLA SANTOS ROCHA", "REBECA ALCANTARA ALVES", "REINALDO NUNES DE OLIVEIRA NETO",
        "TULIO RIBEIRO DE AZEVEDO ROCHA", "VIVIAN IONARA ARAUJO ALVES", "WENDEL ALCANTARA DE SOUZA"
    ],
    "Turma 21 (Pág. 52-53)": [
        "ALEX VITORIO BARROS DO NASCIMENTO", "ANA CLARA BISPO SILVA", "ANA CLARA DE SOUZA ANJOS", "ANA JULIA DALTRO AMARAL",
        "CAUA SOUZA SILVA", "CLARA LUISA MIRANDA TEIXEIRA", "ENZO BARBERINO BIZERRA DIAS", "GABRIEL DE SOUZA OLIVEIRA",
        "GEOVANNA RIBEIRO MARTINS", "GILIARDO NOVAIS DE MOURA", "HYANDRIA CARVALHO FERREIRA", "IAN SANTOS DA SILVA",
        "ISABEL CASTRO E SANTOS CARVALHO", "ISABELLA GOMES DE SOUZA", "ISABELLA XAVIER AMARAL", "JOSYLEIA NASCIMENTO MENEZES",
        "JULIA TELES RIBEIRO", "JULIA SANTOS ARAUJO", "KAMILLE VITORIA DE OLIVEIRA SILVA", "KAROLAINE SILVA SOUZA",
        "KETHELIN VITORIA DOS ANJOS SÁ TELES OLIVEIRA", "LARA CARINE PEREIRA MIRANDA", "LAURA ARAUJO DOURADO DE ATHAYDE",
        "LUKA THIERRY SA TELES DE ARAUJO", "LUNA KELLY MEDEIROS QUEIROZ", "LUNNA NASCIMENTO DIAS", "MARIA CLARA ALVES FERREIRA",
        "MARIA CLARA DE SOUZA MENDES", "MARIA EDUARDA BISPO DOS SANTOS", "MARIANA TEIXEIRA DE SOUZA", "MARIANE DOS ANJOS RIBEIRO",
        "MARYA CLARA ALVES SILVA", "NICOLLY BRITO DE SOUZA", "PEDRO CORDEIRO SANTOS", "PEDRO GABRIEL DOS SANTOS",
        "PEDRO KAUAN SOUZA OLIVEIRA", "VITORIA OLIVEIRA GUIMARAES", "VIVIANNY MORAES PACHECO"
    ],
    "Turma 22 (Pág. 54)": [
        "ANA LUIZA OLIVEIRA ALVES", "ANNA KAROLINA FERREIRA DOS SANTOS", "ANNA KEVELLY FARIAS VIEIRA", "BIANCA SOARES DA SILVA",
        "BRENDA TEIXEIRA VAZ", "CARLOS HENRIQUE SANTOS DE SOUZA", "CARMEN MACIEL ROCHA NETA", "CRYSTAL PIRES NEIVA",
        "DAFINE SOFIA RODRIGUES DE SOUZA", "DAVID DE OLIVEIRA GONCALVES", "EDUARDA DE LIMA SOUZA", "ESTER ALMEIDA BOMFIM",
        "IKARO PIRES DA SILVA", "JOAO VICTOR ANJOS OLIVEIRA", "JULIA CATHARINE SOUZA TELES",
        "LARISSA STEFHANY MACEDO FERREIRA", "LIZ VICTORIA SOARES DE SOUZA", "LUCAS EDUARDO OLIVEIRA NASCIMENTO",
        "LUIZ HENRIQUE MENDES DE MIRANDA SENNA", "MARIA ANTONIA SANTOS DE SOUZA", "MARIA EDUARDA ABREU SOARES DE ATHAYDE",
        "MARIA EDUARDA SANTOS DE OLIVEIRA", "MARIA EDUARDA SOUZA DOS ANJOS DUARTE", "MARIA JULIA DE ANDRADE FERNANDES",
        "MARIA VITORIA RIBEIRO DO NASCIMENTO", "MARYA EDUARDA MENDES RIBEIRO VIEIRA", "MARYA JULIA FERREIRA DA SILVA",
        "PEDRO ARIEL DE SOUZA SANTOS", "ROBERT MARLEY RIBEIRO MOREIRA", "THAUANY BEATRIZ SILVA RODRIGUES",
        "WILLIAN HIDEKI BASTOS HORIO", "YAGO ANJOS DA SILVA"
    ],
    "Turma 23 (Pág. 56)": [
        "ALESSANDRO MIRANDA ALVES", "ANA CLARA OLIVEIRA DE SOUZA", "BEATRIZ JESUS DOS SANTOS", "BRENNDA SOUZA ALCANTARA",
        "CAUA VITOR SILVA SANTOS", "CLARA SANTOS VIANA", "DAVID BRANDAO BARROS", "ELVIS M. DE O. NOVAES SEGUNDO",
        "EMILE MARIA DA S. DOS SANTOS", "EMILY CAVALCANTE BARBOSA", "EVERSON NOVAES TEIXEIRA", "GUILHERME SOUZA RIBEIRO",
        "GUSTAVO BRANDAO VAZ", "GUSTAVO JOSE PIRES DE SOUZA", "IAGO SOUZA SILVA", "IKARO TEIXEIRA CRISPIM",
        "INGRID LORRANE MENDES DE JESUS", "ISABELA NASCIMENTO DOS SANTOS", "JOAO PAULO BRANDAO RIBEIRO",
        "JOAO PEDRO COSTA ALMEIDA", "JOAO VICTOR SANTOS DE SOUZA", "JOSE HIAGO TEIXEIRA DE SOUZA", "KAUANE VIANA DE OLIVEIRA",
        "LARA G. DOS SANTOS SILVA", "LORRANE SANTOS SOUZA", "LUCAS RODRIGUES DE SOUZA", "MARIANE SOUZA BRANDAO",
        "MONICA PIRES S. DA SILVA", "NAIARA ANJOS DE OLIVEIRA", "NAIARA NOVAIS DE SOUZA", "NYQUELE SILVA ARAUJO",
        "PYETRO OLIVEIRA SOUZA", "RENAN OLIVEIRA ALVES", "RUTE PEREIRA OLIVEIRA", "STEFANY OLIVEIRA MENDES",
        "VALERIA GUIMARAES SOUZA", "WANDERSON K. DOS SANTOS PINA", "ISABELA GOMES ARAUJO", "ROBISMAR OLIVEIRA SANTOS"
    ],
    "Turma 24 (Pág. 58)": [
        "ALEXSANDRA ROSA DE SOUZA", "ANA JULIA GUIMARAES MENDES", "CINTIA OLIVEIRA DOS SANTOS", "DANIEL ALVES DE ARAUJO",
        "DAVID RUAN SANTOS DOURADO", "EDUARDO NASCIMENTO ALVES", "EVELYN DA CUNHA ARAUJO", "FLAVIA SOUZA SANTOS",
        "FRANCISCO REIS DOS SANTOS", "GUILHERME SOUZA LEITE", "IRIS DE SOUZA ALVES", "ISABELLA ARAUJO ALVES", "IURE SOUZA SANTOS",
        "JAQUELINE LIMA DE SOUZA", "JOAO VICTOR SILVA PINA", "KLARA ALICE FRANCA RIBEIRO", "LAILA KELY AMORIM DA SILVA",
        "MAICON CLAUDIO SOUZA SANTANA", "MANOEL ALVES PEREIRA", "MARCO ANTONIO SOUZA VIEIRA", "MATEUS FERREIRA SALES",
        "MATHEUS MONTEIRO DOS SANTOS", "NATHAN DE ANDRADE GUEDES", "NATIELY NASCIMENTO DE SOUZA", "NATYELE ANJOS COSTA",
        "PEDRO GABRIEL BARBOSA BRANDAO", "PEDRO HENRIQUE ALVES DOS SANTOS", "RANIEL SOUZA MENDES", "ROBISMAR OLIVEIRA SANTOS",
        "SAVIO RAFAEL CHAVES DOS ANJOS", "SUZANE EVELIN PINTO DE OLIVEIRA", "UANDERSON DE SOUZA", "VICTOR HUGO DE SOUZA TELES",
        "WALISON ALVES BRAZILEIRO", "VICENTE ARAÚJO DA SILVA", "GABRIELLA ALVES DE OLIVEIRA"
    ],
    "Turma 25 (Pág. 60-61)": [
        "ANA CLARA DE SOUZA ARAUJO", "ANA GABRIELA PORTO AZEVEDO", "ANA LUISA OLIVEIRA ALVES", "ANGELICA SOUZA DE JESUS",
        "CAIO GONCALVES BARBOSA", "CARLOS KAUE OLIVEIRA DE JESUS", "CRISTIANO JESUS VIANA", "DAFINE ROBERTA SILVA DOS SANTOS",
        "DEIVID LIMA FERREIRA", "ELOISA NICOLE TEIXEIRA DE SOUZA", "ENDRIO GABRIEL PINTO DA SILVA", "ERICK BUENO DE OLIVEIRA",
        "ERICK SANTOS MACEDO", "FRANCIELE SANTOS DE SOUZA", "GABRIEL SOUSA DA SILVA", "GLENDA MEDEIROS AMORIM",
        "GUILHERME ARAUJO DE OLIVEIRA", "GUSTAVO ALCANTARA DA SILVA", "HENRY GOMES MERA", "ISAC NILTON MARTINS DE SOUZA",
        "IZABELA SOUZA SANTOS", "IZANIA DE SOUZA OLIVEIRA", "JOAO FELIPE DOS SANTOS BARROS", "JOAO VITOR SANTOS DE ALCANTARA",
        "KEVEN ANTONY SILVA BARROS", "LARA YSABELA SILVA BRANDÃO", "LARISSA DOS SANTOS OLIVEIRA", "LUIS GABRIEL BRANDAO SANTOS",
        "LUIZ GABRIEL SOUZA SANTOS", "MARIA EDUARDA SOUZA DE OLIVEIRA", "MARIA ESTEFANE NOVAES DA SILVA",
        "MARYANA DE OLIVEIRA SOUZA", "NAIANE DE SOUZA", "PAULO FRANCISCO MACEDO DE JESUS", "PAULO HENRIQUE PINTO NASCIMENTO",
        "PEDRO HENRIQUE MEDEIROS SANTOS", "RAIKA EDUARDA PINTO SILVA", "SAMILE DOS ANJOS BRAGA", "SAMIRA SANTOS MENDES",
        "SAMUEL OLIVEIRA DOS SANTOS", "THAYSON ALVES BRANDAO", "VITOR SOUZA OLIVEIRA", "YASMIN OLIVEIRA DA SILVA",
        "VICENTE ARAUJO DA SILVA"
    ],
    "Turma 26 (Pág. 62)": [
        "ANA CLARA OLIVEIRA SANTOS", "ANA PAULA ARAUJO DE SOUZA", "ANALI SILVA SANTOS", "DAIZA DE SOUZA MATOS",
        "DANIEL DE SOUZA MENDES", "EDIENE MEDEIROS SANTOS", "EVERTON CONCEICAO MENDES", "FABRICIO MENDES DE OLIVEIRA",
        "FELIPE DOS SANTOS SOUZA", "GUSTAVO BRANDAO ARAUJO", "HELOYSE MENDES", "JOAO PEDRO ARAUJO TEIXEIRA",
        "JOAO VITOR SILVA DOS ANJOS", "LEVI GUILHERME SANTOS ALCANTARA", "MARCIO PAULO SOUZA MENDES",
        "MARIA CLARA ALMEIDA RODRIGUES", "MARTA SANTOS SOUZA", "NATIELY MACEDO DE SOUZA", "NICOLAS RYAN BARBOSA MARTINS",
        "OTAVIO DE SOUZA LIMA", "PABLO MENDES", "PAULO ROBERTO OLIVEIRA SILVA", "PEDRO HENRIQUE OLIVEIRA DE JESUS",
        "PRISCILA DA SILVA MIRANDA", "SAMUEL DANTAS SILVA", "TAISLANE MENDES MONTEIRO", "VICTOR APARECIDO SOUZA MENDES",
        "VINICIUS MENDES ARAUJO", "GABRIELE NASCIMENTO SANTOS", "YASMIN PAMELA OLIVEIRA COPQUE", "LAZARO SANTOS JESUS",
        "VITORIA OLIVEIRA GUIMARÃES"
    ],
    "Turma 27 (Pág. 63)": [
        "ADSON ARAUJO ALVES", "ANA CLARA ANJOS BARROS", "ANNA VITORIA FIDELES DE SOUZA", "ARYEL MATHEUS OLIVEIRA LOPES",
        "BISMARK ANJOS DOS SANTOS", "DEIVSON RUFINO DE SOUZA", "ELLEN KAILANE ARAUJO DOS SANTOS", "EMILLY OLIVEIRA BRANDAO",
        "ENZO GABRIEL MENDES SANTANA", "ERICK RIAN DE OLIVEIRA FERREIRA", "IAGO MATHEUS BARBOSA SILVA", "JULIA DE SOUZA SANTOS",
        "KELLY NAIANE DE NOVAIS ANJOS", "LARA LORRANE ROCHA FERREIRA", "LUNNA RIHANNA ALVES SANTOS", "MARINA DA SILVA FERREIRA",
        "MIRELE SILVA BRANDAO", "NATALIA MENDES", "NATIELE SANDRA MENDES DE JESUS", "RAQUEL RODRIGUES ALVES DE SOUZA",
        "SAMILLY SOUZA LEITE", "SHEILA SILVA DE OLIVEIRA", "VITORIA EDUARDA BARROS ALVES", "MAINARA DE SOUZA OLIVEIRA"
    ],
    "Turma 28 (Pág. 64)": [
        "ALANNA DOS ANJOS TEIXEIRA", "ANA BEATRIZ ANJOS THOMAZ", "BEATRIZ JESUS DA SILVA", "BRUNA SILVA SANTOS",
        "CECILIA SOUZA DA SILVA", "DANTE BELO SOUZA", "DAVI OLIVEIRA LIMA", "EMILLY MENDES DO NASCIMENTO",
        "ERICK SOUZA DA SILVA", "HENRIQUE DA SILVA SOUZA", "HEVILY SANTOS MENDES", "IASMIM AMARILES SILVA SOUZA",
        "ISABELA SANTOS MARTINS", "ISIS VALENTINA SOUZA ASSUNÇÃO", "IZABELA OLIVEIRA SANTANA", "JEFERSON ALVES DE MENEZES",
        "JOANA RAISSA SILVA DE ARAUJO", "JOAO FELIPE NAS-CIMENTO DOS ANJOS", "JULIANE DE SOUZA SANTOS",
        "KARINE CLARA MENDES TEIXEIRA", "LAIZA TAINA ALVES DE SOUZA", "LAURA PEREIRA DE LIMA", "LORRANE DOURADO SOUZA",
        "LUIS KASSIO SA TELES DE SOUZA", "MARIA EDUARDA SOUZA GOMES", "MARIA LUISA REIS SANTANA BRANDAO",
        "MARIA VITORIA ANJOS TEIXEIRA", "PEDRO ALCANTARA DOS SANTOS", "PEDRO KEIVISON MENDES DE SOUZA",
        "THAUANY RODRIGUES DE SOUZA", "YASMIM SOUZA DA SILVA", "YASMIN LANA MEDEIROS DOS SANTOS",
        "YASMIN MOURA JESUS BRANDAO", "ISABELLA GOMES DE SOUZA"
    ],
    "Turma 29 (Pág. 66)": [
        "ALEXANDRE DE JESUS DOS SANTOS", "ANA SARAH VIEIRA DO NASCIMENTO", "DHEIVERSON JESUS DOS ANJOS",
        "GABRIEL ATHAYDE ARAUJO SILVA", "GABRIEL VINICIUS MARIANO SANTIAGO", "PEDRO CAUAN ALVES LIMA", "THIAGO ALCANTARA VIEIRA"
    ],
    "Turma 30 (Pág. 67)": [
        "ADRIELE ALVES DE SOUZA", "ALISSON KAUE RODRIGUES FERNANDES", "ANA LUISA MENDES DOS SANTOS", "ANDERSON BARBOSA DA PAZ",
        "ANDRE GABRIEL DE BRITO SILVA", "CARINE GONCALVES DE SOUZA", "DIEGO MARQUES DOS SANTOS",
        "EDUARDO QUEIROZ GASPAR DE SOUZA", "GABRIEL LAZARO DE SOUZA", "GIOVANNA KETELYN DE SA SELIS", "GUSTAVO FERNANDES SANTOS",
        "GUSTAVO JOSE DE SOUZA", "IAN FERNANDES ARAUJO", "ISLANE DOS SANTOS BISPO", "JARDEL SANTOS DE OLIVEIRA",
        "JOAQUIM ARAUJO DE CARVALHO", "JULIA OLIVEIRA BRITO", "KAREN VITORIA SANTOS SOUZA", "KAUAN SOUZA SILVA",
        "KERLLON CASSIO OLIVEIRA PONTES", "LEIDIANE ROSA DOS SANTOS", "LUCAS SANTOS BRITO", "MARIA EDUARDA MARQUES ARAUJO",
        "MARIA VITORIA BENICIO VAZ", "MARIO AUGUSTO QUEIROZ DE OLIVEIRA", "MARISSOL SANTOS RIBEIRO", "MATHEUS SILVA BRAGA",
        "MATHEUS SILVA NOVAIS", "NAJLA DOS SANTOS NEVES", "NATHALY LIMA DA SILVA", "NELIA VITORIA SOUZA MENDES",
        "PABLO KEVIN VIEIRA SILVA", "PEDRO G. NOVAIS DO NASCIMENTO", "RAFAEL SILVA TEIXEIRA", "THIAGO INACIO DOS SANTOS",
        "VITORIA ROSA DE OLIVEIRA", "AMANDA SOUZA QUADRO", "ADEILSON SILVA FERNANDES", "JOÃO PEDRO SILVA FERNANDES"
    ],
    "Turma 31 (Pág. 68)": [
        "ÁLVARO ANTÔNIO PEREIRA MARTINS", "AMANDA MARTINS RODRIGUES", "ANA CAROLINA JESUS OLIVEIRA", "ANA JULIA SOUZA MACEDO",
        "ANA LUISA VIEIRA SANTOS", "ANAILTON DOS SANTOS LIMA", "ANDERSON GUIMARAES EVANGELISTA JUNIOR",
        "CAUAN GABRIEL DOS ANJOS SOUZA", "CLARA MAISE VIEIRA DE SOUZA", "CRISTINA BORGES DE OLIVEIRA",
        "DANIFI RAICA OLIVEIRA DOS ANJOS", "EMILY THYINE CORDEIRO DE OLIVEIRA", "DIEGO SANTOS SOUZA", "EDWIGES RIBEIRO SA TELES",
        "GEOVANA DA GLORIA SANTOS NERES DE SOUZA", "GEOVANA DE SOUZA SANTOS", "ISABELLA BASTOS DE OLIVEIRA SANTOS",
        "JOABSON DOS SANTOS", "JOAO MATHEUS NOBREGA MARIANO", "JOAO PEDRO SILVA OLIVEIRA", "JULIA MENDES BARBOSA",
        "JULIANO BUENO SANTOS", "KEILA OLIVEIRA SANTOS", "LARA MEIRE AMORIM DOS SANTOS", "LARA SODRE SOUZA",
        "LUIS AUGUSTO MARTINS BENTO", "MARIA JULIA ALVES LIMA", "MARIA LUIZA FARIAS DE PAULA", "MAYCK JESUS NERES DA SILVA",
        "MICAELY ALVES SANTANA", "MICHELLE TAUANE MENDES", "NAILSON JOSE CASSIMIRO", "NATALIA MEL SANTOS SILVA",
        "PEDRO ANTONIO RABELO LIMA", "PHILLIPE BRYAN SANTOS ROCHA", "RAYSSA MACHADO OLIVEIRA", "TIAGO SANTOS BRITO",
        "VICTOR EMANUEL RIBEIRO SODRE FERREIRA", "YANE FERREIRA LIMA", "CAILANE SILVA OLIVEIRA"
    ],
    "Turma 32 (Pág. 69)": [
        "ADRIELLY MACEDO BELO", "ALICIA VITORIA ALCANTARA DE SOUZA", "AMANDA SOUZA QUADRO", "ANAIAN SOUZA",
        "BEATRIZ BASTOS DOS SANTOS", "CAIO SOUZA COSTA", "CECILIA FERREIRA DOS SANTOS", "CRIS LAUANNE DOS SANTOS CAMILO",
        "DANIELE RANIA FERNANDES GONCALVES", "ELVIS ALVES DO CARMO", "EMILY FARIAS DA SILVA", "GISELLE DA SILVA SANTOS",
        "GENEILSON ALVES DOS SANTOS", "HENZO MATHEUS ALVES DE SOUZA", "ISAAC ANTONIO DE SOUZA", "JAYANNE DE SOUZA PEREIRA",
        "JOANA OLIVEIRA DOS SANTOS", "JOAO FELIPE SOARES ANDRADE", "JULIA SANTOS RAMOS", "KAUAN CASSIMIRO DE MENEZES",
        "KELLY SOUZA SANTOS", "LAIS EDUARDA ALVES TEIXEIRA", "LARA LUISE SOUZA MACEDO", "LAZARO GABRIEL SILVA SOUZA",
        "LEANDERSON RODRIGUES DA SILVA", "LEVY MADUREIRA NUNES", "LILIANE VITORIA DE CARVALHO", "LUAN HENRIQUE SOUZA DOS ANJOS",
        "LUAN MATHEUS OLIVEIRA FERREIRA", "LUIZ PHELIPE ALVES DE OLIVEIRA", "MARCIO VITOR DOS ANJOS ALVES",
        "MARIA VITORIA OLIVEIRA DOS SANTOS", "MARINA NUNES SANTOS", "MATEUS ALVES DA SILVA",
        "NICOLAS RAMOS MIRANDA DE ARAUJO", "PAULO VITOR MATOS ARAUJO", "RAFAELA BARRETO SANTOS", "SUZANE SANTOS SILVA",
        "TAMIRES DA SILVA DE JESUS", "TIAGO VICENTE DE SOUZA"
    ],
    "Turma 33 (Pág. 70)": [
        "ADRIAN WISLEI BRAGA DOS SANTOS", "ANA CAROLINA ROSA PINTO", "ANA CLARA P. DA SILVA OLIVEIRA", "CAIO PIETRO DE OLIVEIRA",
        "CALIANE BONFIM DA SILVA", "CAMILE VITORIA CRUZ DE SOUZA", "CARLOS EDUARDO ARAUJO DE OLIVEIRA",
        "CEZAR GOMES DOS SANTOS JUNIOR", "DAVID ALVES QUEIROZ", "DIOGO LUIGY A. MARTINS", "EMILY XAVIER AMORIM",
        "GUILHERME SENNA COELHO", "FLORA LUZ LADEIA GIOVANINI FERREIRA", "GABRIEL ARAUJO VIEIRA", "GABRIEL SANTOS DAMACENA",
        "GILMAR DOS ANJOS SANTOS", "HENRIQUE TAKEO DE PAULA YAMAUTI", "HENZO SA TELES SILVA", "IGOR DE SOUZA SILVA",
        "ISANDRA DOS SANTOS DE SOUZA", "JOSE JARIO MIRANDA CHAVES", "KAMILY VITORIA VIEIRA FAGUNDES", "LEDIANE DOS ANJOS SANTOS",
        "LUCAS DOS ANJOS MENDES", "LUIZ FELIPE SOUZA SANTOS", "MARIA CLARA DA SILVA MELO", "MARIA EDUARDA DOS ANJOS MATOS",
        "MARIA HELENA DE OLIVEIRA SOUZA", "MARIA LUINE VIEIRA FARIAS", "MONIKE ANJOS DE SOUZA",
        "PEDRO HENRIQUE ALVES SANTANA DE SENA", "PIETRO LOPES DOS SANTOS", "RAISSA SILVA SOUZA",
        "SARA LORRANE PEREIRA DOS ANJOS", "SARAH SOUZA CORREIA", "SUEDSON D. OLIVEIRA PRUDENCIO", "TIAGO RAMOS SILVA",
        "WEBSON DE JESUS ALMEIDA", "GAAHL SANTIAGO SOUZA CORREIA", "MYLLENA JESUS DE OLIVEIRA"
    ],
    "Turma 34 (Pág. 71)": [
        "ADRIELLE SILVA SANTOS", "AGATA SANTOS DA SILVA", "AGATHA VITORIA SANTOS ALMEIDA", "ANA CLARA ROCHA SOUZA",
        "ANA CRISTINA NOGUEIRA DE SOUZA", "ANDERSON SILVA GONCALVES", "ANNA KAROLLINY SOUZA OLIVEIRA",
        "BRUNO FERREIRA DE OLIVEIRA", "CAMILY VITORIA DE SOUZA", "CARLOS EDUARDO SOUZA VIEIRA DE OLIVEIRA",
        "EDUARDA LOURANA DE OLIVEIRA MIRANDA", "ESTHER MENDES ALCANTARA", "EVELIN MELO BARBOSA", "GISELLE FRANCA SANTOS",
        "HENDRIK VICTOR NOVAIS DA SILVA", "JULIA SA TELES BARROS", "KAUANE SILVA OLIVEIRA",
        "KAUANNE GABRYELLY RIBEIRO SANTIAGO", "KELVIN ALEF SOUZA TEIXEIRA", "KEMILY AQUINO OLIVEIRA",
        "KEVELIN LORRANE OLIVEIRA BRITO", "LIVIA SILVA DE SOUZA", "LUIS FELIPE SOUSA SANTOS", "MAIRANE ARAUJO DA SILVA",
        "MARIA LAURA PIRES DE MIRANDA SENNA", "MARIANA ALVES SOUZA", "MARIANA DE SOUZA SILVA", "MARJORIE SILVA SOUZA",
        "MISAEL DOS SANTOS VIEIRA", "PEDRO BARROS PIRES DE CARVALHO", "RAFAEL MATOS DE NOVAIS", "SOPHIA SANTANA DE SOUZA",
        "TAINA LIMA DE ABREU", "YASMIN NASCIMENTO RIBEIRO"
    ],
    "Turma 35 (Pág. 72)": [
        "ANA CLARA DOS SANTOS OLIVEIRA", "ANA KAROLAYNE SANTOS SOUZA", "ANDRE MARCOS DOURADO", "ANNA LUISA DE ALMEIDA RIBEIRO",
        "ASAPH DE ALMEIDA FERNANDES", "BIANCA GABRIELLY COSTA ALCANTARA", "BRENO NUNES PINHEIRO DE ALMEIDA",
        "DANIELA ALVES DA SILVA", "DAVID MACHADO LOPES", "EMILLY AQUINO MARIANO", "GUILHERME MENDES VASCONCELOS",
        "GUSTAVO DE SOUZA SA TELES", "HENRY GABRIEL DE OLIVEIRA FARIAS", "HEVILLYN VICTORIA ANJOS LOPES", "ICARO MADUREIRA ALVES",
        "ISIS MAILLENN SOUZA GOMES", "ITALO HENRIQUE OLIVEIRA ARAUJO", "JESSICA RAIANE MENDES PEREIRA",
        "JHONATAS KAUAN RODRIGUES ARAUJO", "JOAO OLIVEIRA DE JESUS", "JULIA ROSA OLIVEIRA DE SOUZA", "KAUA ALCANTARA DE SOUZA",
        "KAUAN ALVES ARAUJO", "KAUANY PAULA DE SOUZA", "LUIS FELIPE SOUZA DA SILVA", "LUIS FERNANDO ARAUJO SANTANA",
        "MARCUS DAVID DOS ANJOS", "MARIA EDUARDA ANDRADE SILVA", "MARIA EDUARDA TEIXEIRA MENDES",
        "MAYANE VITORIA BRANDAO TEIXEIRA", "MAYKE GUILHERME SOUZA MOREIRA", "PEDRO LUCAS DE ARAUJO ANDRADE",
        "PYETRO OLIVEIRA MACEDO", "RAELLY DE SOUZA ALCANTARA", "RUAN GABRIEL SOUZA SANTOS", "SABRINA MIRANDA PADUA",
        "SUANE DOS ANJOS MARTINS", "THAYEME OLIVEIRA MENDES", "MARIA EDUARDA CARVALHO"
    ],
    "Turma 36 (Pág. 73)": [
        "ANA BRISA SILVA SOUZA", "ANA PAULA DOS SANTOS VIEIRA", "ANDRE VITOR OLIVEIRA ARAUJO", "BARBARA PEREIRA DE OLIVEIRA",
        "BENAMI SANTANA RODRIGUES", "BERNARDO SOUZA LOPES", "BRENO FELIX BRANDAO", "CARLOS HENRIQUE DE SOUZA SANTANA",
        "DANIELA SOUZA LIMA", "DAVI SOUZA VIEIRA", "DEIVSON SOUZA SANTOS", "EMILY THAINE CORDEIRO DE OLIVEIRA",
        "ERICA ANJOS DOS SANTOS", "FABRICIO MENDES DE SOUZA", "FELIPE ANJOS BARROS", "FLAVIO DANIEL MENDES GOMES DE OLIVEIRA",
        "ISABELA DE SOUZA OLIVEIRA", "JAMILE DOS SANTOS BARBOSA", "JANARA HELLEN LASSO BRANDAO", "JHENIFFER RODRIGUES FEITOZA",
        "JOANNA LUIZA SOUZA DE OLIVEIRA", "JORGE HENRIQUE MENDES DE OLIVEIRA", "JUAN FERREIRA DOS SANTOS",
        "KAUAN LIMA DOS ANJOS", "LAILA MANUELA ANJOS DE SOUZA", "LAUDICELIA ARAUJO DE OLIVEIRA", "LETICIA ALCANTARA DOS SANTOS",
        "MARCIO EMANOEL DE SOUZA CHAVES", "MARCOS MENDES PINA DE ALENCAR", "MARIANA SILVA SOUZA", "MATHEUS FERREIRA DOS ANJOS",
        "MAXWEL DE ALCANTARA OLIVEIRA", "NAIARA DE SOUZA", "RAISSA BUENO DE SOUZA", "RUTIELY AZEVEDO DE SOUZA",
        "TAISSA NICOLLI AQUINO DE OLIVEIRA", "VITORYA LHIVIA BRANDAO DE SOUSA"
    ],
    "Turma 37 (Pág. 74)": [
        "ALICIA VAZ OLIVEIRA", "ANA GABRIELA SANTOS NASCIMENTO", "ARIEL OLIVEIRA MENDES", "ARIEL OLIVEIRA MENDES (IVANESSA)",
        "CLERISTON RAI MENDES DOS ANJOS", "DENISE ARAUJO ALVES", "DIOGO MIRANDA DE SOUZA", "EDINEI SILVA PINTO",
        "ERICA TELES SOUZA", "ERIK VICTOR OLIVEIRA DE SOUZA", "FELIPY MARCOS ANJOS DOS SANTOS", "FILEMON JESUS DA SILVA",
        "GABRIEL CAETANO TELES BRANDAO", "GEOVANA GABRIELLY DE SOUZA SANTOS", "GIOVANNA LUIZA BRANDAO LAZARO",
        "GUSTAVO HENRIQUE LIBERATO", "GUSTAVO RODRIGUES GASPAR", "GUSTAVO SANTOS MENDES DA SILVA", "IAGO OLIVEIRA MENDES",
        "IASMIM DE OLIVEIRA MENDES", "IASMIN DA SILVA BRANDAO", "IRYS MEL NOVAIS SANTANA", "JOAO VITOR ANJOS SALDANHA",
        "JULIA MENDES OLIVEIRA", "KAILANE JESUS SANTOS", "LARISSA TAUANY SANTOS GOMES", "LUCAS BARRETO FRAGA",
        "MARIA VITORIA BRANDAO DOS ANJOS", "RAFAELLA SOUZA SOARES", "THAINA CLARISSA DA SILVA BRANDAO", "THALIA MENDES",
        "UALACE SOUZA DA SILVA", "VITORIA POLIANA PINA DE OLIVEIRA", "YASMIM ALENCAR DOS SANTOS", "MARCIO EMANOEL",
        "KAMILY VITORIA VIERA FAGUNDES"
    ],
    "Turma 38 (Pág. 75)": [
        "ANDRYA DANIELLY ARAUJO DOS SANTOS", "CASSIO ATHAYDE RABELO", "DANIELA DA SILVA SANTOS", "DIEGO VIEIRA SOARES",
        "DIOGO DOS SANTOS SOUZA", "EDIANE BARBOSA DOS ANJOS", "ELIANE JESUS DA SILVA", "ELLEN ENEDINA TELES FERNANDES",
        "ERICK DE SOUZA OLIVEIRA", "EVELIN DE SOUZA ALVES", "FABIANA BARBOSA NASCIMENTO",
        "FERNANDA THAYLLA OLIVEIRA DA SILVA", "GABRIELA MARTINS SOUZA", "GEORGE DAVID SILVA BRANDAO",
        "GRAZIELE MIRANDA DE OLIVEIRA", "JOAO ANTONIO DE SOUZA VAZ", "JOAO CARLOS SOUZA LIMA", "JOVANA DOS ANJOS NUNES",
        "KELY ANJOS DOS SANTOS", "KEMILLE VITORIA REIS LAZARO", "LUIZ HENRIQUE MENDES DE JESUS", "MAIARA CRUZ DE OLIVEIRA",
        "MAISA PINTO SOUZA", "MARCIO ANDREI ALCANTARA SANTOS", "MARCUS VINICIUS SOUZA TEIXEIRA", "MARIANE MIRANDA DOS SANTOS",
        "MATHEUS DOS SANTOS VIEIRA", "PALOMA ALVES DE OLIVEIRA", "PEDRO HENRIQUE FERREIRA GOMES", "RAFAEL SOUZA SA TELES",
        "RAFAELLA DE SOUZA SANTOS", "RAY JOSE DA CONCEICAO SANTOS", "RENAN BARBOSA JORGE", "RUBENS ALVES FERREIRA",
        "SABRINA BASTOS OLIVEIRA", "SOPHIA ALCANTARA DE SOUZA BRANDAO", "TATIANE MARTINS ARAUJO", "VANESSA ARAUJO GUEDES",
        "VIRGILIO VITORIO DE ARAUJO NETO", "VITOR DA SILVA ALMEIDA"
    ],
    "Turma 39 (Pág. 76)": [
        "ACASSIO DA SILVA MARTINS", "ALISSON GASPAR DE SOUZA", "ANALY JESUS DOS SANTOS", "ARIEL SOUZA SILVA",
        "CLEISSON SOUZA DA SILVA", "EDINARIO DOS SANTOS OLIVEIRA", "ELVIS ALENCAR DOS SANTOS SILVA",
        "EMILE CONCEICAO OLIVEIRA DOS ANJOS", "EZIELTON CONCEICAO MENDES", "GABRIEL PEREIRA DE OLIVEIRA",
        "GEANE MENDES DOS SANTOS", "GEAZI TEIXEIRA GOMES", "GUILHERME BRAGA DE SOUZA", "GUILHERME SOUZA DA SILVA",
        "HENRIQUE DOS ANJOS BARROS", "INGREDY DREGER DE JESUS", "JORGE GABRIEL FEITOSA RIBEIRO", "JOSE NILTON NASCIMENTO PINTO",
        "LARA INGRID NERIS DE AQUINO", "LEILTON DA SILVA MENDES", "LUDE DE SOUZA FERREIRA", "LUNA DA SILVA ARAUJO",
        "LUNA MARIA PEREIRA DE SOUZA", "MICAEL BARBOZA DA SILVA", "MICHEL SANTOS OLIVEIRA", "NAELE DE SOUZA",
        "PEDRO MIGUEL NASCIMENTO SANTOS", "RAILA SOUZA AMORIM", "RENILSON DE SOUZA SILVA", "RICKELME SOUZA SILVA",
        "SAMUEL SOUZA SILVA", "THAUA VICTOR DE OLIVEIRA SANTOS", "UALISSON RUAN ARAUJO SOUZA", "VANESSA SOUZA MENDES",
        "JOVANA ALVES DOS SANTOS", "ISANDRA DOS SANTOS DE SOUZA"
    ],
    "Turma 40 (Pág. 77)": [
        "ADRIANA DE SOUZA LIMA", "ANA CAMILA FERREIRA ALVES", "ANA CLARA DE SOUZA SANTOS", "ANDRE LUIS BARROS GABRIEL",
        "CARLOS EDUARDO SANTOS DE OLIVEIRA", "DIEGO COSTA VIEIRA", "GABRIEL OLIVEIRA BENTO DE SOUZA", "JAMILE DE SOUZA GOMES",
        "JOAO HENRIQUE NOVAES DE SOUZA", "JOAO VICTOR MEDEIROS NASCIMENTO", "KARINNA DOS ANJOS ARAUJO",
        "KEYLLA PRISCILA ANJOS DE JESUS", "LORRANE CONCEICAO DA SILVA", "LUAN GABRIEL DOS SANTOS BRITO", "LUIZ DA PAZ OLIVEIRA",
        "MAIRLA SOPHIA ANJOS DE SOUZA", "MARIA FLOR LOPES DE SOUZA", "MARIA LUIZA OLIVEIRA BRANDAO", "NICOLAS SANTOS DE SOUZA",
        "RAYANE SANTOS DE SOUZA", "VIVIANE GUALBERTO DE SOUZA", "YASMIN APARECIDA SANTOS TEIXEIRA",
        "KEVELIN LORRANE OLIVEIRA BRITO", "LUANE VITORIA DE ALCANTARA NUNES"
    ],
    "Turma 41 (Pág. 78)": [
        "ANA PAULA ALVES DE SOUZA", "BIANCA RODRIGUES DAMASCENA", "CAILAN NASCIMENTO ALENCAR", "CLEITON DE JESUS SA TELES",
        "DAVI DOS REIS MARQUES", "DAVID VIEIRA BRAGA", "DEBORA CECILIA ALVES MARTINS", "GABRIELE MARTINS DA SILVA",
        "HUDSON DIOGO BATISTA RODRIGUES DE SOUZA", "ISABELLA SANTOS MENDES", "JANDERSON ALVES DE JESUS",
        "JOAO FELIPE TEIXEIRA DOS SANTOS", "JOSEH PEDRO DE ARAUJO FERREIRA", "KAUAN LUCAS ARAUJO DE SOUZA",
        "LARISSA CARVALHO DA SILVA", "LARISSA SILVA SOUZA", "LAURA LISS ANJOS OLIVEIRA", "LIVIA PEREIRA DOS ANJOS",
        "LUANA SOUZA BONFIM", "LUANE VITORIA DE ALCANTARA NUNES", "MARIA EDUARDA CARVALHO DE OLIVEIRA",
        "MARIA JULLIA SOUZA SANTOS", "MATEUS ANTONIO SOUZA OLIVEIRA", "MILENA SOUZA SA TELES", "NICOLLY DE SOUZA OLIVEIRA",
        "PEDRO HENRIQUE TEIXEIRA FERREIRA", "STEFANNY DA SILVA DE SOUZA", "THAINE GEOVANA MERA DE OLIVEIRA"
    ],
    "Turma 42 (Pág. 79)": [
        "ADRIELE NUNES DA SILVA", "ANA PAULA DE SOUZA BRANDAO", "ARIEL GONCALVES GOMES", "ARIEL SOUZA BISPO",
        "BRUNO FELIX BRANDAO", "CAMILY SOUZA ALVES", "CLEYSIELE SILVA DO CARMO", "DAVID HARLEI DOS SANTOS NOVAES",
        "EDIELCK TEIXEIRA SILVA", "GABRIELA MARTINS DE SOUZA", "GABRIELLY SOUZA SANTOS", "GLEIBISON DE SOUZA LIMA",
        "GUSTAVO XAVIER DOS SANTOS", "HERCULES JESUS MARQUES", "JEANDERSON SANTOS LIMA", "JOANA KELY VIEIRA DE SOUZA",
        "LEANDRO SILVA DE SOUZA", "LUIZ EDUARDO SOUZA VIEIRA", "MAENA OLIVEIRA PONTES",
        "MARCOS ALEXANDRE DE OLIVEIRA CONCEICAO", "MARCOS NOVAES SANTOS", "MARIA LUISA SOUZA SILVA",
        "MATEUS NOVAIS DE OLIVEIRA", "MATHEUS OLIVEIRA PIRES", "RAI SANTOS", "RAISA BENEDITO DA SILVA",
        "RAISSA SILVA FERNANDES", "RAQUEL PEREIRA DA SILVA", "RUAN ALVES SANTANA", "TAILANE ALVES DE SOUZA",
        "TALISSON NEI DIAS NOVAES", "TIAGO SILVA SANTOS", "MARIA EDUARDA DOS ANJOS MATOS"
    ],
    "Turma 43 (Pág. 80)": [
        "AYLA CAMILY MENDES DA SILVA", "FABRICIO REIS DE OLIVEIRA", "GUILHERME MESSIAS PAZ", "GUTIERRY OLIVEIRA SOUZA",
        "IGOR NUNES DA SILVA", "JOAO MIGUEL SANTOS ARAUJO", "KARINA ALMEIDA CARVALHO", "LUCAS BARBOSA BENIGNO",
        "LUCAS MANOEL NUNES", "NATALIA TEIXEIRA NASCIMENTO", "RAI PEREIRA DA ROCHA", "VITOR GABRIEL SANTOS SILVA"
    ]
}

def normalizar(nome):
    n = unicodedata.normalize('NFKD', nome)
    n = ''.join(c for c in n if not unicodedata.combining(c))
    n = re.sub(r'\s+', ' ', n).strip().upper()
    return n

# Análise de ocorrências
todos_nomes_normalizados = {}
ocorrencias_por_aluno = {}
turmas_processadas = {}

total_registros_brutos = 0

for turma_nome, alunos in raw_turmas.items():
    turmas_processadas[turma_nome] = []
    for a in alunos:
        total_registros_brutos += 1
        a_limpo = re.sub(r'\s+', ' ', a).strip()
        norm = normalizar(a_limpo)
        
        # Guarda nome original representativo mais bem formatado
        if norm not in todos_nomes_normalizados:
            todos_nomes_normalizados[norm] = a_limpo
            ocorrencias_por_aluno[norm] = []
        ocorrencias_por_aluno[norm].append(turma_nome)
        turmas_processadas[turma_nome].append(a_limpo)

# Alunos únicos
alunos_unicos = sorted(list(todos_nomes_normalizados.values()), key=lambda x: normalizar(x))

# Alunos repetidos
repetidos = {norm: turmas for norm, turmas in ocorrencias_por_aluno.items() if len(turmas) > 1}

print(f"Total de turmas analisadas: {len(raw_turmas)}")
print(f"Total de registros brutos de alunos nas turmas: {total_registros_brutos}")
print(f"Total de alunos ÚNICOS (sem repetição): {len(alunos_unicos)}")
print(f"Total de nomes que aparecem em mais de uma turma: {len(repetidos)}")

print("\n--- NOMES QUE APARECEM EM MAIS DE UMA TURMA ---")
for norm, turmas in sorted(repetidos.items()):
    nome_repr = todos_nomes_normalizados[norm]
    print(f"- {nome_repr} ({len(turmas)} ocorrências): {', '.join(turmas)}")

# Salvar resultados em JSON
with open('c:/Users/Ian Santos/Desktop/VSCODE/censoceeps/scripts/alunos_extraidos_unicos.json', 'w', encoding='utf-8') as f:
    json.dump({
        "total_turmas": len(raw_turmas),
        "total_registros_brutos": total_registros_brutos,
        "total_alunos_unicos": len(alunos_unicos),
        "alunos_unicos": alunos_unicos,
        "alunos_repetidos_entre_turmas": {
            todos_nomes_normalizados[norm]: turmas for norm, turmas in repetidos.items()
        },
        "por_turma": turmas_processadas
    }, f, ensure_ascii=False, indent=2)

print("\nArquivo JSON salvo em scripts/alunos_extraidos_unicos.json com sucesso!")
