import express from 'express';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import dotenv from 'dotenv';
import {initDb,run,get,all} from './db.js';
dotenv.config();const app=express(),port=Number(process.env.PORT||3000),secret=process.env.JWT_SECRET||'development-secret-change-me',publicDir=path.join(path.dirname(fileURLToPath(import.meta.url)),'public'),RACES=['Branca','Preta','Parda','Amarela','Indígena','Prefiro não responder'];
app.use(express.json({limit:'100kb'}));app.use(express.static(publicDir));
function auth(req,res,next){try{const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!t)throw Error();req.user=jwt.verify(t,secret);next()}catch{res.status(401).json({error:'Sessão inválida ou expirada.'})}}
function admin(req,res,next){return req.user.cargo==='ADMINISTRADOR'?next():res.status(403).json({error:'Acesso exclusivo da administração.'})}
function error(res,e){console.error(e);res.status(500).json({error:'Não foi possível concluir a operação.'})}
app.post('/api/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),u=await get('SELECT * FROM usuarios WHERE email=? AND ativo=1',[email]);if(!u||!bcrypt.compareSync(String(req.body.senha||''),u.senha_hash))return res.status(401).json({error:'E-mail ou senha inválidos.'});const usuario={id:u.id,nome:u.nome,email:u.email,cargo:u.cargo};res.json({token:jwt.sign(usuario,secret,{expiresIn:'8h'}),usuario})}catch(e){error(res,e)}});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/grupos',auth,async(_,res)=>{try{res.json(await all('SELECT * FROM grupos_escolares WHERE ativo=1 ORDER BY tipo,nome'))}catch(e){error(res,e)}});
app.post('/api/grupos',auth,admin,async(req,res)=>{const{tipo,nome,turno}=req.body;if(!['TURMA','SETOR'].includes(tipo)||!String(nome||'').trim()||!String(turno||'').trim())return res.status(400).json({error:'Tipo, nome e turno são obrigatórios.'});try{const r=await run('INSERT INTO grupos_escolares(tipo,nome,turno) VALUES(?,?,?)',[tipo,nome.trim(),turno.trim()]);res.status(201).json({id:r.lastID})}catch{res.status(409).json({error:'Este grupo já está cadastrado.'})}});
app.post('/api/admin/usuarios',auth,admin,async(req,res)=>{const{nome,email,senha,cargo='ENTREVISTADOR'}=req.body;if(!nome||!email||!senha||!['ADMINISTRADOR','ENTREVISTADOR'].includes(cargo))return res.status(400).json({error:'Dados obrigatórios inválidos.'});try{const r=await run('INSERT INTO usuarios(nome,email,senha_hash,cargo) VALUES(?,?,?,?)',[nome.trim(),email.trim().toLowerCase(),bcrypt.hashSync(senha,12),cargo]);res.status(201).json({id:r.lastID})}catch{res.status(409).json({error:'Este e-mail já está cadastrado.'})}});
app.post('/api/entrevistas',auth,async(req,res)=>{const b=req.body,required=['vinculo','grupo_escolar_id','faixa_etaria','cor_raca','conhece_ancestralidade','ja_conversou_sobre'];if(required.some(k=>b[k]===undefined||b[k]==='')||!['ESTUDANTE','FUNCIONARIO'].includes(b.vinculo)||!RACES.includes(b.cor_raca))return res.status(400).json({error:'Preencha os campos obrigatórios com opções válidas.'});try{if(!await get('SELECT id FROM grupos_escolares WHERE id=? AND ativo=1',[b.grupo_escolar_id]))return res.status(400).json({error:'Turma ou setor inválido.'});const r=await run('INSERT INTO entrevistas(entrevistador_id,vinculo,grupo_escolar_id,faixa_etaria,cor_raca,conhece_ancestralidade,geracao_alcancada,povo_indigena,ja_conversou_sobre,ambientes_conversa) VALUES(?,?,?,?,?,?,?,?,?,?)',[req.user.id,b.vinculo,b.grupo_escolar_id,b.faixa_etaria,b.cor_raca,b.conhece_ancestralidade,b.geracao_alcancada||null,String(b.povo_indigena||'').trim()||null,b.ja_conversou_sobre,JSON.stringify(Array.isArray(b.ambientes_conversa)?b.ambientes_conversa:[])]);res.status(201).json({id:r.lastID,message:'Entrevista registrada com sucesso.'})}catch(e){error(res,e)}});
app.get('/api/dashboard',auth,async(req,res)=>{try{const v=['ESTUDANTE','FUNCIONARIO'].includes(req.query.vinculo)?req.query.vinculo:null,cl=v?' WHERE e.vinculo=?':'',p=v?[v]:[];const [total,cor,vinculo,grupos,idades]=await Promise.all([get(`SELECT COUNT(*) total FROM entrevistas e${cl}`,p),all(`SELECT e.cor_raca label,COUNT(*) value FROM entrevistas e${cl} GROUP BY e.cor_raca ORDER BY value DESC`,p),all(`SELECT e.vinculo label,COUNT(*) value FROM entrevistas e${cl} GROUP BY e.vinculo`,p),all(`SELECT g.nome label,COUNT(e.id) value FROM grupos_escolares g LEFT JOIN entrevistas e ON e.grupo_escolar_id=g.id${v?' AND e.vinculo=?':''} WHERE g.ativo=1 GROUP BY g.id ORDER BY value DESC`,p),all(`SELECT e.faixa_etaria label,COUNT(*) value FROM entrevistas e${cl} GROUP BY e.faixa_etaria`,p)]);res.json({total:total.total,cor,vinculo,grupos,idades})}catch(e){error(res,e)}});
app.get('/api/export.csv',auth,async(_,res)=>{try{const rows=await all('SELECT e.id,e.vinculo,g.tipo grupo_tipo,g.nome grupo,g.turno,e.faixa_etaria,e.cor_raca,e.conhece_ancestralidade,e.geracao_alcancada,e.ja_conversou_sobre,e.ambientes_conversa,e.criado_em FROM entrevistas e JOIN grupos_escolares g ON g.id=e.grupo_escolar_id ORDER BY e.id'),esc=x=>`"${String(x??'').replaceAll('"','""')}"`;res.type('text/csv').attachment('censo-entrevistas.csv').send('\ufeff'+['id,vinculo,grupo_tipo,grupo,turno,faixa_etaria,cor_raca,conhece_ancestralidade,geracao_alcancada,ja_conversou_sobre,ambientes_conversa,criado_em',...rows.map(r=>Object.values(r).map(esc).join(','))].join('\n'))}catch(e){error(res,e)}});
app.get('*',(_,res)=>res.sendFile(path.join(publicDir,'index.html')));initDb().then(()=>app.listen(port,()=>console.log(`Censo CEEPS v2: http://localhost:${port}`))).catch(e=>{console.error(e);process.exit(1)});
